/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMediaflowsWebhookRouteImport } from './routes/api/mediaflows/webhook'
import { Route as ApiDebugLatestAssetRouteImport } from './routes/api/debug/latest-asset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaflowsWebhookRoute = ApiMediaflowsWebhookRouteImport.update({
  id: '/api/mediaflows/webhook',
  path: '/api/mediaflows/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugLatestAssetRoute = ApiDebugLatestAssetRouteImport.update({
  id: '/api/debug/latest-asset',
  path: '/api/debug/latest-asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/debug/latest-asset': typeof ApiDebugLatestAssetRoute
  '/api/mediaflows/webhook': typeof ApiMediaflowsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/debug/latest-asset': typeof ApiDebugLatestAssetRoute
  '/api/mediaflows/webhook': typeof ApiMediaflowsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/debug/latest-asset': typeof ApiDebugLatestAssetRoute
  '/api/mediaflows/webhook': typeof ApiMediaflowsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/debug/latest-asset' | '/api/mediaflows/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/debug/latest-asset' | '/api/mediaflows/webhook'
  id: '__root__' | '/' | '/api/debug/latest-asset' | '/api/mediaflows/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDebugLatestAssetRoute: typeof ApiDebugLatestAssetRoute
  ApiMediaflowsWebhookRoute: typeof ApiMediaflowsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mediaflows/webhook': {
      id: '/api/mediaflows/webhook'
      path: '/api/mediaflows/webhook'
      fullPath: '/api/mediaflows/webhook'
      preLoaderRoute: typeof ApiMediaflowsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/latest-asset': {
      id: '/api/debug/latest-asset'
      path: '/api/debug/latest-asset'
      fullPath: '/api/debug/latest-asset'
      preLoaderRoute: typeof ApiDebugLatestAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDebugLatestAssetRoute: ApiDebugLatestAssetRoute,
  ApiMediaflowsWebhookRoute: ApiMediaflowsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
